#!/usr/bin/zsh

if [[ $# -eq 0 ]]; then
    echo "usage: $0 IMGUR-GALLERY-URL (like http://imgur.com/a/UlFLb)"
    exit 0
fi

ghash=$(echo "$@" | awk -F'/' '{ print $NF }')

web http://imgur.com/ajaxalbums/getimages/$ghash/hit.json | jq -r '.data.images[] | [.hash, .ext] | @tsv' | awk -F'\t' '{ print "http://i.imgur.com/"$1$2 }'
