#!/usr/bin/zsh

if [[ $# -eq 0 ]]; then
    echo "usage: $0 IMGUR-GALLERY-URL (like http://imgur.com/a/UlFLb)"
    exit 0
fi

web "$@" | egrep -v '(thumb|placeholder)' | perl -ne 'if (m{"(//i.imgur.com/[^"]+)"}) { print "http:$1\n" }'
